#include "problem_002.h"

/*Problem 2

Even Fibonacci numbers


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:	4613732
 */



int problem_002() {
	
	int sum = 0;
	
	const int limit = 400000;
	
	int a = 2;
	int b = 8;
	int c = 4*b + a;
	
	sum = (a + b);
	
	while (c < limit) {
		// Add the next term to the sum.
		sum += c;
		
		// Advance each term forward one.
		a = b;
		b = c;
		c = 4*b + a;
	}
	
}
